# Generated by Django 4.0.5 on 2022-07-03 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='women',
            options={'verbose_name': 'Женщина', 'verbose_name_plural': 'Женщины'},
        ),
    ]
